# Generated by Django 3.2.7 on 2021-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketers',
            name='role',
            field=models.CharField(default='all', max_length=20),
            preserve_default=False,
        ),
    ]
